Update workflow to allow parallel job

diff --git a/.github/workflows/e2e_api_tests.yml b/.github/workflows/e2e_api_tests.yml
--- a/.github/workflows/e2e_api_tests.yml
+++ b/.github/workflows/e2e_api_tests.yml
@@ -66,9 +66,16 @@ env:
     E2E_COVERAGE: ./tests/pw/playwright-report/e2e/coverage-report/coverage.json
 
 jobs:
-    tests:
-        name: e2e_api tests
-        runs-on: ubuntu-latest
+
+    e2e_tests:
+        name: e2e tests
+        runs-on: ubuntu-24.04 # todo: replace with ubuntu-latest after january 2025
+        timeout-minutes: 20
+        strategy:
+            fail-fast: false
+            matrix:
+                shardIndex: [1, 2, 3, 4, 5]
+                shardTotal: [5]
 
         steps:
             - name: Checkout testing repo
@@ -115,18 +122,6 @@ jobs:
                       cd tests/pw
                       npm run start:env
 
-            # Set permalink structure
-            - name: Set Permalink structure
-              working-directory: tests/pw
-              run: |
-                  npm run wp-env run tests-cli wp rewrite structure /%postname%/
-
-            # Activate theme
-            - name: Activate theme:Storefront
-              working-directory: tests/pw
-              run: |
-                  npm run wp-env run tests-cli wp theme activate storefront
-
             # Get Playwright version
             - name: Get installed Playwright version
               id: playwright-version
@@ -161,13 +156,13 @@ jobs:
             #     npm run pw:deps-only
 
             # Run e2e tests
-            - name: 🧪 Run e2e tests
+            - name: 🧪 Run e2e tests-${{ matrix.shardIndex }}
               id: e2e-test
               if: success() && (github.event_name != 'workflow_dispatch' || ( github.event_name == 'workflow_dispatch' && (github.event.inputs.testsuite == 'E2E' || github.event.inputs.testsuite == 'All')))
-              timeout-minutes: 40
+              timeout-minutes: 15
               working-directory: tests/pw
               run: |
-                  npm run test:e2e
+                  npm run test:e2e -- --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
 
             # Run e2e coverage
             - name: 🧪 Run e2e coverage
@@ -175,15 +170,6 @@ jobs:
               working-directory: tests/pw
               run: |
                   npm run test:e2e:coverage
-
-            # Run api tests
-            - name: 🧪 Run api tests
-              id: api-test
-              if: always() && steps.wp-env.outcome == 'success' && ( github.event_name != 'workflow_dispatch'  || ( github.event_name == 'workflow_dispatch' && (github.event.inputs.testsuite == 'API' || github.event.inputs.testsuite == 'All')))
-              timeout-minutes: 5
-              working-directory: tests/pw
-              run: |
-                  npm run test:api
 
             # Prepare test summary
             - name: Prepare test summary
@@ -196,26 +182,127 @@ jobs:
                       const script = require("./tests/pw/utils/gitTestSummary.ts")
                       return await script({github, context, core})
 
-            # # Find PR comment
-            # - name: Find PR comment by github-actions[bot]
-            #   id: find-comment
-            #   if: github.event_name == 'pull_request'
-            #   uses: peter-evans/find-comment@v3
-            #   with:
-            #       issue-number: ${{ github.event.pull_request.number }}
-            #       comment-author: 'github-actions[bot]'
-            #       body-includes: Tests Summary
+            # Backup Database
+            - name: Backup Database
+              if: always() && steps.wp-env.outcome == 'success'
+              working-directory: tests/pw
+              run: |
+                  npm run wp-env run tests-cli wp db export wp-data/db.sql
 
-            # # Post test summary as PR comment
-            # - name: Create or update PR comment
-            #   if: github.event_name == 'pull_request'
-            #   uses: peter-evans/create-or-update-comment@v4
-            #   with:
-            #       comment-id: ${{ steps.find-comment.outputs.comment-id }}
-            #       issue-number: ${{ github.event.pull_request.number }}
-            #       body: ${{ steps.prepare-test-summary.outputs.result }}
-            #       reactions: hooray
-            #       edit-mode: replace
+            # Upload artifacts
+            - name: Archive test artifacts (screenshots, HTML snapshots, Reports)
+              uses: actions/upload-artifact@v4
+              if: always() && steps.debug-log.outcome == 'success'
+              with:
+                  name: test-artifact-${{ matrix.shardIndex }}
+                  path: |
+                      tests/pw/wp-data
+                      tests/pw/playwright
+                      tests/pw/playwright-report
+                  if-no-files-found: ignore
+                  retention-days: 1
+
+    api_tests:
+        name: api tests
+        runs-on: ubuntu-24.04
+        timeout-minutes: 10
+
+        steps:
+            - name: Checkout testing repo
+              id: clone-dokan-lite
+              uses: actions/checkout@v4
+
+            - name: Use desired version of NodeJS
+              uses: actions/setup-node@v4
+              with:
+                  node-version: 20
+                  cache: npm
+
+            - name: Composer install and build (Dokan-lite)
+              run: |
+                  composer i --no-dev -o || composer update --no-dev -o
+
+            - name: Npm install and build (Dokan-lite)
+              run: |
+                  npm ci || npm i
+                  npm run build
+
+            # Install test dependencies
+            - name: Install test dependencies
+              working-directory: tests/pw
+              run: |
+                  npm ci || npm i
+
+            # Create wp debuglog file
+            - name: Create wp debuglog file
+              id: debug-log
+              working-directory: tests/pw
+              run: |
+                  mkdir -p wp-data && touch wp-data/debug.log
+
+            # Start wordpress environment
+            - name: Start WordPress Env
+              id: wp-env
+              uses: nick-fields/retry@v3
+              with:
+                  timeout_minutes: 5
+                  max_attempts: 2
+                  retry_on: error
+                  command: |
+                      cd tests/pw
+                      npm run start:env
+
+            # Get Playwright version
+            - name: Get installed Playwright version
+              id: playwright-version
+              working-directory: tests/pw
+              run: |
+                  echo "PLAYWRIGHT_VERSION=$(npm ls @playwright/test --json | jq --raw-output '.dependencies["@playwright/test"].version')" >> $GITHUB_ENV
+
+            # Cache browser binaries, cache key is based on Playwright version and OS
+            - name: Cache playwright binaries
+              id: playwright-cache
+              uses: actions/cache@v4
+              with:
+                  path: |
+                      ~/.cache/ms-playwright
+                  key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
+                  restore-keys: |
+                      ${{ runner.os }}-playwright-
+
+            # Install browser binaries & OS dependencies if cache missed
+            - name: Install Playwright browser binaries & OS dependencies
+              id: pw-install
+              if: steps.playwright-cache.outputs.cache-hit != 'true'
+              working-directory: tests/pw
+              run: |
+                  npm run pw:browser-with-deps
+
+            # # Install only the OS dependencies if cache hit  not needed
+            # - name: Install Playwright OS dependencies
+            #   if: steps.playwright-cache.outputs.cache-hit == 'true'
+            #   working-directory: tests/pw
+            #   run: |
+            #     npm run pw:deps-only
+
+            # Run API tests
+            - name: 🧪 Run api tests
+              id: api-test
+              if: always() && steps.wp-env.outcome == 'success' && ( github.event_name != 'workflow_dispatch'  || ( github.event_name == 'workflow_dispatch' && (github.event.inputs.testsuite == 'API' || github.event.inputs.testsuite == 'All')))
+              working-directory: tests/pw
+              run: |
+                  npm run test:api:pro
+
+            # Prepare test summary
+            - name: Prepare test summary
+              id: prepare-test-summary
+              if: always() && steps.clone-dokan-lite.outcome == 'success'
+              uses: actions/github-script@v7
+              with:
+                  result-encoding: string
+                  script: |
+                      const script = require("./tests/pw/utils/gitTestSummary.ts")
+                      return await script({github, context, core})
 
             # Backup Database
             - name: Backup Database
@@ -229,10 +316,139 @@ jobs:
               if: always() && steps.debug-log.outcome == 'success'
               uses: actions/upload-artifact@v4
               with:
-                  name: test-artifact
+                  name: test-artifact-api
                   path: |
                       tests/pw/wp-data
                       tests/pw/playwright
                       tests/pw/playwright-report
                   if-no-files-found: ignore
-                  retention-days: 30
+                  retention-days: 1
+
+    merge-reports:
+        # Merge reports after playwright-tests, even if some shards have failed
+        if: ${{ !cancelled() }}
+        needs: [e2e_tests, api_tests]
+        runs-on: ubuntu-24.04
+        timeout-minutes: 5
+
+        # Override reports path specifically for this job
+        env:
+            API_TEST_RESULT: ./tests/pw/all-reports/test-artifact-api/playwright-report/api/summary-report/results.json
+            API_COVERAGE: ./tests/pw/all-reports/test-artifact-api/playwright-report/api/coverage-report/coverage.json
+            E2E_TEST_RESULT: ./tests/pw/all-reports/merged-summary.json
+            E2E_COVERAGE: ./tests/pw/all-reports/merged-coverage.json
+
+        steps:
+            - name: Checkout testing repo
+              id: clone-dokan-lite
+              uses: actions/checkout@v4
+
+            - name: Use desired version of NodeJS
+              uses: actions/setup-node@v4
+              with:
+                  node-version: 20
+                  cache: npm
+
+            - name: Install test dependencies
+              working-directory: tests/pw
+              run: |
+                  npm ci || npm i
+
+            - name: Download all test artifacts from GitHub Actions
+              id: download-test-artifacts
+              uses: actions/download-artifact@v4
+              with:
+                  path: tests/pw/all-reports
+                  pattern: test-artifact-*
+
+            - name: Move all blob report folder contents into a single folder
+              working-directory: tests/pw/all-reports
+              run: |
+                  mkdir -p all-blob-reports
+                  find . -type f -path "*/blob-report/*" -exec mv {} all-blob-reports/ \;
+              #   ls all-blob-reports
+
+            - name: Generate HTML Report
+              id: generate-html-report
+              working-directory: tests/pw
+              run: |
+                  npx playwright merge-reports --reporter html ./all-reports/all-blob-reports
+                  mv playwright-report ./all-reports/html-report
+
+            - name: Clean all files except ZIPs
+              working-directory: tests/pw
+              run: |
+                  find all-reports/all-blob-reports -mindepth 1 ! -name "*.zip" -exec rm -rf {} +
+
+            - name: Generate merged summary report
+              id: merge-summary-report
+              if: steps.download-test-artifacts.outcome == 'success'
+              working-directory: tests/pw
+              run: |
+                  npx ts-node ./utils/mergeSummaryReport.ts
+
+            - name: Generate merged coverage report
+              id: merge-coverage-report
+              if: steps.download-test-artifacts.outcome == 'success'
+              working-directory: tests/pw
+              run: |
+                  npx ts-node ./utils/mergeCoverageSummary.ts
+
+            # Prepare test summary
+            - name: Prepare test summary
+              id: prepare-test-summary
+              if: always() && steps.merge-summary-report.outcome == 'success'
+              uses: actions/github-script@v7
+              with:
+                  result-encoding: string
+                  script: |
+                      const script = require("./tests/pw/utils/gitTestSummary.ts")
+                      return await script({github, context, core})
+
+            # Find PR comment
+            - name: Find PR comment by github-actions[bot]
+              id: find-comment
+              if: github.event_name == 'pull_request'
+              uses: peter-evans/find-comment@v3
+              with:
+                  issue-number: ${{ github.event.pull_request.number }}
+                  comment-author: 'github-actions[bot]'
+                  body-includes: Tests Summary
+
+            # Post test summary as PR comment
+            - name: Create or update PR comment
+              if: github.event_name == 'pull_request'
+              uses: peter-evans/create-or-update-comment@v4
+              with:
+                  comment-id: ${{ steps.find-comment.outputs.comment-id }}
+                  issue-number: ${{ github.event.pull_request.number }}
+                  body: ${{ steps.prepare-test-summary.outputs.result }}
+                  reactions: hooray
+                  edit-mode: replace
+
+            - name: Upload final test artifact
+              if: always() && steps.download-test-artifacts.outcome == 'success'
+              uses: actions/upload-artifact@v4
+              with:
+                  name: final-test-artifact
+                  path: tests/pw/all-reports
+                  if-no-files-found: ignore
+                  retention-days: 7
+
+            # - name: Publish HTML report to GH Pages
+            #   if: always() && steps.generate-html-report.outcome == 'success'
+            #   uses: peaceiris/actions-gh-pages@v4
+            #   with:
+            #       github_token: ${{ secrets.GITHUB_TOKEN }}
+            #       publish_branch: gh-pages
+            #       publish_dir: ./tests/pw/all-reports/html-report
+            #       destination_dir: ${{ github.event.pull_request.number || github.sha }}
+            #       keep_files: true
+            #       user_name: 'github-actions[bot]' # This will be the username that gets stamped in the repo commit
+            #       user_email: 'github-actions[bot]@users.noreply.github.com' # This will be the user email that gets stamped in the repo com
+
+
+            # - name: Test results
+            #   if: always()
+            #   run: |
+            #       echo "https://$GITHUB_REPOSITORY_OWNER.github.io/${GITHUB_REPOSITORY#*/}"
